### ISSUE TITLE
Releases available as packs at https://github.com/LogtalkDotOrg/wordnet

### ISSUE THREAD

**Issue by pmoura** [ekaf/wordnet-prolog#5]
I have made the current releases available as packs at https://github.com/LogtalkDotOrg/wordnet Thanks for making the releases available and let me know if I missed something or got some detail wrong.

**Comment by ekaf** [comment]
The above project does not mention the OEWN 2022 package released six months ago.
 It is not an issue here, as  our package list is up to date: https://github.com/ekaf/wordnet-prolog/releases

**Comment by pmoura** [comment]
Added a pack manifest file for the OEWN 2022 package (https://github.com/LogtalkDotOrg/wordnet/commit/9e7b685d8d1b465e863cc4dbc77df8334ce0e645). Thanks for the heads-up and for your work in these packages.
